CompanyRegister.Web/Models/ViewModels/CompanyEmployeesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CompaniesRegiter.Models;

namespace CompanyRegister.Web.Models.ViewModels
{
    public class CompanyEmployeesViewModel
    {
        public string CompanyName { get; set; }

        public List<Employee> Employees { get; set; }
    }
}

CompanyRegister.Web/Models/ViewModels/CompanyInternsViewModel.cs
using System.Collections.Generic;
using CompaniesRegiter.Models;

namespace CompanyRegister.Web.Models.ViewModels
{
    public class CompanyInternsViewModel
    {
        public string CompanyName { get; set; }

        public List<Intern> Interns { get; set; }
    }
}

CompanyRegister.Web/Controllers/CompaniesController.cs
namespace CompanyRegister.Web.Controllers
{
    using System.Linq;
    using AutoMapper;
    using CompaniesRegister.Services.Implementations;
    using CompaniesRegiter.Models;
    using Models.BindingModels;
    using Models.DTOs;
    using Models.ViewModels;
    using Microsoft.AspNetCore.Mvc;

    public class CompaniesController : Controller
    {
        private CompanyServices CompanyServices { get;}

        private IMapper Mapper { get; }

        public CompaniesController(CompanyServices services, IMapper mapper)
        {
            this.CompanyServices = services;
            this.Mapper = mapper;
        }

        public IActionResult Index()
        {
            var companies = this.CompanyServices.GetLastThreeCompanies();

            return View(companies);
        }

        public IActionResult All()
        {
            var companies = this.CompanyServices.GetAllCompanies();
            return View(companies);
        }

        public IActionResult Register()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Register(RegisterCompanyBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            }

            var company = this.Mapper.Map<Company>(model);
            var isTaken = this.CompanyServices.NameIsTaken(company.Name);

            if (isTaken)
            {
                ModelState.AddModelError("Name", "Name is already taken!");
                return this.View();
            }
            this.CompanyServices.AddToDatabase(company);
            return RedirectToAction("Details",new{id=company.Id,slug=company.Name});
        }

        public IActionResult Details(int id,string slug)
        {
            var company = this.CompanyServices.GetCompanyById(id);

            if (company == null || company.Name != slug)
            {
                return NotFound();
            }

            return this.View(company);
        }

        public IActionResult CompanyEmployees(int id, string slug)
        {
            var company = this.CompanyServices.GetCompanyById(id);

            if (company == null || company.Name != slug)
            {
                return NotFound();
            }

            var employees = company.Employees.ToList();
            var vm = new CompanyEmployeesViewModel
            {
                Employees = employees,
                CompanyName = company.Name
            };

            return this.View(vm);
        }

        public IActionResult CompanyInterns(int id, string slug)
        {
            var company = this.CompanyServices.GetCompanyById(id);

            if (company == null || company.Name != slug)
            {
                return NotFound();
            }

            var interns = company.Interns.ToList();
            var vm = new CompanyInternsViewModel()
            {
                CompanyName = company.Name,
                Interns = interns
            };

            return this.View(vm);
        }

        public IActionResult Edit(int id, string slug)
        {
            var company = this.CompanyServices.GetCompanyById(id);

            if (company == null || company.Name != slug)
            {
                return NotFound();
            }

            return this.View(company);
        }

        [HttpPost]
        public IActionResult Edit(EditCompanyBindingModel bm,int id)
        {
            var company = CompanyServices.GetCompanyById(id);

            if (bm.Name != null)
            {
                var isTaken = CompanyServices.NameIsTaken(bm.Name);
                if (isTaken)
                {
                    ModelState.AddModelError("Name","This name is already taken");
                    return this.View(company);
                }

                company.Name = bm.Name;
            }

            if (bm.FoundationDate != null)
            {
                company.FoundationDate = bm.FoundationDate.Value;
            }

            if (bm.PictureUrl != null)
            {
                company.PictureUrl = bm.PictureUrl;
            }

            this.CompanyServices.UpdateCompany(company);
            this.ViewData["edit"] = "You have successfully edited this company!";
            return this.View(company);
        }

        public IActionResult Delete(int id,string slug)
        {
            var company = CompanyServices.GetCompanyById(id);
            if (company == null || company.Name != slug)
            {
                return NotFound();
            }

            return this.View(company);
        }

        public IActionResult FinalDelete(int id, string slug)
        {
            var company = CompanyServices.GetCompanyById(id);
            if (company == null || company.Name != slug)
            {
                return NotFound();
            }

            var dto = new FinalDeleteNameDTO()
            {
                Name = company.Name
            };

            this.CompanyServices.RemoveCompany(company);

            return this.View(dto);
        }
    }
}

CompanyRegister.Web/Controllers/EmployeesController.cs
namespace CompanyRegister.Web.Controllers
{
    using System.Linq;
    using AutoMapper;
    using CompaniesRegister.Services.Implementations;
    using CompaniesRegiter.Models;
    using Models.BindingModels;
    using Models.DTOs;
    using Microsoft.AspNetCore.Mvc;

    public class EmployeesController : Controller
    {
        private EmployeeServices EmployeeServices { get;}

        private CompanyServices CompanyServices { get;}

        private IMapper Mapper { get;}

        public EmployeesController(
            EmployeeServices employeeServices, 
            CompanyServices companyServices,
            IMapper mapper)
        {
            this.EmployeeServices = employeeServices;
            this.CompanyServices = companyServices;
            this.Mapper = mapper;
        }

        public IActionResult Index()
        {
            var employees = EmployeeServices.GetLastThreeEmployees();
            return View(employees);
        }

        public IActionResult All()
        {
            var employees = EmployeeServices.GetAllEmployees();
            return this.View(employees);
        }

        public IActionResult Register()
        {
            var companies = CompanyServices.GetAllCompanies();
            return this.View(companies);
        }

        [HttpPost]
        public IActionResult Register(RegisterEmployeeBindingModel bm)
        {
            var expLevels = new[] {"A","B","C","D"};

            if (!expLevels.Contains(bm.ExperinceLevel))
            {
                ModelState.AddModelError("ExperinceLevel", "Experince Level must be \"A\", \"B\", \"C\", \"D\"");
                var companies = CompanyServices.GetAllCompanies();
                return this.View(companies);
            }

            var employee = this.Mapper.Map<Employee>(bm);
            this.EmployeeServices.AddEmployee(employee);
            return RedirectToAction("Details", new { id = employee.Id, slug = employee.Name });
        }

        public IActionResult Details(int id,string slug)
        {
            var employee = EmployeeServices.GetEmployeeById(id);

            if (employee == null || employee.Name != slug)
            {
                return NotFound();
            }

            return this.View(employee);
        }

        public IActionResult Edit(int id, string slug)
        {
            var employee = EmployeeServices.GetEmployeeById(id);
            var comapnies = CompanyServices.GetAllCompanies();

            if (employee == null || employee.Name != slug)
            {
                return NotFound();
            }

            var employeeDto = new EditEmployeeDto()
            {
                Employee = employee,
                Companies = comapnies
            };

            return this.View(employeeDto);
        }

        [HttpPost]
        public IActionResult Edit(EditEmployeeBindingModel bm,int id)
        {
            var employee = EmployeeServices.GetEmployeeById(id);

            var expLevels = new[] { "A", "B", "C", "D" };

            if (bm.ExperinceLevel != null && !expLevels.Contains(bm.ExperinceLevel))
            {
                ModelState.AddModelError("ExperinceLevel", "Experince Level must be \"A\", \"B\", \"C\", \"D\"");
                var dtoComp = CompanyServices.GetAllCompanies();
                var dto = new EditEmployeeDto()
                {
                    Companies = dtoComp,
                    Employee = employee
                };
                return this.View(dto);
            }

            EditEmployee(bm, employee);

            this.EmployeeServices.UpdateEmployee(employee);
            var companies = this.CompanyServices.GetAllCompanies();
            employee = EmployeeServices.GetEmployeeById(id);

            var employeeDto = new EditEmployeeDto()
            {
                Employee = employee,
                Companies = companies
            };

            this.ViewData["edit"] = "You have successfully edited this employee!";

            return this.View(employeeDto);
        }

        public IActionResult Delete(int id, string slug)
        {
            var employee = EmployeeServices.GetEmployeeById(id);

            if (employee == null || employee.Name != slug)
            {
                return NotFound();
            }

            return this.View(employee);
        }

        public IActionResult FinalDelete(int id, string slug)
        {
            var employee = EmployeeServices.GetEmployeeById(id);
            if (employee == null || employee.Name != slug)
            {
                return NotFound();
            }

            var dto = new FinalDeleteNameDTO()
            {
                Name = employee.Name
            };

            this.EmployeeServices.RemoveEmployee(employee);

            return this.View(dto);
        }

        private static void EditEmployee(EditEmployeeBindingModel bm, Employee employee)
        {
            if (bm.ExperinceLevel != null)
            {
                employee.ExperinceLevel = bm.ExperinceLevel;
            }

            if (bm.Name != null)
            {
                employee.Name = bm.Name;
            }

            if (bm.CompanyId != null)
            {
                employee.CompanyId = bm.CompanyId.Value;
            }

            if (bm.PictureUrl != null)
            {
                employee.PictureUrl = bm.PictureUrl;
            }

            if (bm.Salary != null)
            {
                employee.Salary = bm.Salary.Value;
            }

            if (bm.StartDate != null)
            {
                employee.StartDate = bm.StartDate.Value;
            }

            if (bm.VacationDays != null)
            {
                employee.VacationDays = bm.VacationDays.Value;
            }
        }
    }
}

CompanyRegister.Web/Controllers/InternsController.cs
using AutoMapper;
using CompaniesRegister.Services.Implementations;
using CompaniesRegiter.Models;
using CompanyRegister.Web.Models.BindingModels;
using CompanyRegister.Web.Models.DTOs;
using Microsoft.AspNetCore.Mvc;

namespace CompanyRegister.Web.Controllers
{
    public class InternsController : Controller
    {
        private InternServices InternServices { get;}

        private CompanyServices CompanyServices { get; }

        private IMapper Mapper { get; }

        public InternsController(
            InternServices internServices,
            CompanyServices companyServices,
            IMapper mapper)
        {
            this.InternServices = internServices;
            this.CompanyServices = companyServices;
            this.Mapper = mapper;
        }

        public IActionResult Index()
        {
            var interns = InternServices.GetLastThreeInterns();
            return View(interns);
        }

        public IActionResult Details(int id,string slug)
        {
            var intern = InternServices.GetInternById(id);

            if (intern == null || intern.Name != slug)
            {
                return NotFound();
            }

            return this.View(intern);
        }

        public IActionResult All()
        {
            var interns = InternServices.GetAllInterns();
            return this.View(interns);
        }

        public IActionResult Register()
        {
            var companies = this.CompanyServices.GetAllCompanies();
            return this.View(companies);
        }

        [HttpPost]
        public IActionResult Register(RegisterInternBindingModel bm)
        {
            if (!ModelState.IsValid)
            {
                var companies = this.CompanyServices.GetAllCompanies();
                return this.View(companies);
            }

            var intern = this.Mapper.Map<Intern>(bm);
            this.InternServices.AddIntern(intern);

            return this.RedirectToAction("Details",new{id=intern.Id,slug=intern.Name});
        }

        public IActionResult Delete(int id, string slug)
        {
            var intern = InternServices.GetInternById(id);

            if (intern == null || intern.Name != slug)
            {
                return NotFound();
            }

            return this.View(intern);
        }

        public IActionResult FinalDelete(int id, string slug)
        {
            var intern = InternServices.GetInternById(id);
            if (intern == null || intern.Name != slug)
            {
                return NotFound();
            }

            var dto = new FinalDeleteNameDTO()
            {
                Name = intern.Name
            };

            this.InternServices.RemoveIntern(intern);

            return this.View(dto);
        }

        public IActionResult Edit(int id,string slug)
        {
            var intern = InternServices.GetInternById(id);
            var comapnies = CompanyServices.GetAllCompanies();

            if (intern == null || intern.Name != slug)
            {
                return NotFound();
            }

            var internDto = new EditInternDto()
            {
                Intern = intern,
                Companies = comapnies
            };

            return this.View(internDto);
        }

        [HttpPost]
        public IActionResult Edit(EditInternBindingModel bm, int id)
        {
            var intern = InternServices.GetInternById(id);

            if (!ModelState.IsValid)
            {
                var comapnies = CompanyServices.GetAllCompanies();

                var internDto = new EditInternDto()
                {
                    Intern = intern,
                    Companies = comapnies
                };

                return this.View(internDto);
            }

            EditIntern(bm, intern);

            this.InternServices.UpdateIntern(intern);
            var companies = this.CompanyServices.GetAllCompanies();
            intern = InternServices.GetInternById(id);

            var dto = new EditInternDto()
            {
                Intern = intern,
                Companies = companies
            };
            this.ViewData["edit"] = "You have successfully edited this intern!";

            return this.View(dto);
        }

        private static void EditIntern(EditInternBindingModel bm, Intern intern)
        {
            if (bm.Name != null)
            {
                intern.Name = bm.Name;
            }
            if (bm.CompanyId != null)
            {
                intern.CompanyId = bm.CompanyId.Value;
            }

            if (bm.PictureUrl != null)
            {
                intern.PictureUrl = bm.PictureUrl;
            }

            if (bm.Salary != null)
            {
                intern.Salary = bm.Salary.Value;
            }

            if (bm.StartDate != null)
            {
                intern.StartDate = bm.StartDate.Value;
            }

            if (bm.DaysOfInternship != null)
            {
                intern.DaysOfInternship = bm.DaysOfInternship.Value;
            }
        }
    }
}

CompanyRegister.Web/Views/Companies/All.cshtml
@{
    ViewData["Title"] = "All Companies";
}
@model List<Company>
<h2 id="compH">All Companies</h2>

@if (Model.Any())
{
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Foundation Date</th>
            <th>Empoyees Count</th>
            <th>Interns Count</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var company in Model)
        {
            <tr>
                <td>
                    @company.Id
                </td>
                <td>
                    @company.Name
                </td>
                <td>
                    @company.FoundationDate.ToShortDateString()
                </td>
                <td>
                    @company.Employees.Count()
                </td>
                <td>
                    @company.Interns.Count()
                </td>
                <td>
                    <a class="btn btn-primary" asp-controller="Companies" asp-action="Details" asp-route-id="@company.Id" asp-route-slug="@company.Name">Info</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <h4 style="margin-top: 25px;font-weight: bolder">There are no companies registered! Be the first one to register one?</h4>
}

CompanyRegister.Web/Views/Companies/CompanyEmployees.cshtml
@model CompanyEmployeesViewModel
@{
    ViewData["Title"] = $"Employees of {Model.CompanyName}";
}

<h2 style="margin-top: 55px; text-align: center;">@ViewData["Title"]</h2>

<div style="margin-top: 25px; width: 60%" class="container">
    <div class="list-group">
        @foreach (var employee in Model.Employees)
        {
            <a asp-controller="Employees" asp-action="Details" asp-route-id="@employee.Id" asp-route-slug="@employee.Name" class="list-group-item">
                <h3 class="list-group-item-heading">Name: @employee.Name</h3>
                <p class="list-group-item-text">Salary: @employee.Salary</p>
            </a>
        }
    </div>
</div>

CompanyRegister.Web/Views/Companies/CompanyInterns.cshtml
@model CompanyInternsViewModel
@{
    ViewData["Title"] = $"Interns of {Model.CompanyName}";
}

<h2 style="margin-top: 55px; text-align: center;">@ViewData["Title"]</h2>

<div style="margin-top: 25px; width: 60%" class="container">
    <div class="list-group">
        @foreach (var intern in Model.Interns)
        {
            <a asp-controller="Interns" asp-action="Details" asp-route-id="@intern.Id" asp-route-slug="@intern.Name" class="list-group-item">
                <h3 class="list-group-item-heading">Name: @intern.Name</h3>
                <p class="list-group-item-text">Salary: @intern.Salary</p>
            </a>
        }
    </div>
</div>

CompanyRegister.Web/Views/Companies/Delete.cshtml
@model Company
@{
    ViewData["Title"] = $"Delete {Model.Name}";
}

<h2 style="text-align: center; margin-top: 55px;">Are you sure you want to delete @Model.Name?</h2>
<div style="text-align: center; margin-top: 15px;">
    <img src="@Model.PictureUrl" alt="Alternate Text"style="width: 400px;" />
</div>
<div style="text-align: center; margin-top: 15px;">
    <a style="font-size: 25px;" class="btn btn-danger" asp-controller="Companies" asp-action="FinalDelete" asp-route-id="@Model.Id" asp-route-slug="@Model.Name">Delete</a>
</div>

CompanyRegister.Web/Views/Companies/Details.cshtml
@model Company
@{
    ViewData["Title"] = $"Details for {Model.Name}";
}

<h2 style="margin-top: 55px; text-align: center;">@ViewData["Title"]</h2>

<ul class="list-group" style="width: 65%; margin: auto; margin-top: 25px;">
    <li class="list-group-item"><strong>Id:</strong> @Model.Id</li>
    <li class="list-group-item"><strong>Name:</strong> @Model.Name</li>
    <li class="list-group-item"><strong>Foundation Date:</strong> @Model.FoundationDate.ToShortDateString()</li>
    <li class="list-group-item"><img style="width: 50%" src="@Model.PictureUrl" /></li>
</ul>
<div class="text-center">
    <a asp-controller="Companies" asp-action="CompanyEmployees" asp-route-id="@Model.Id" asp-route-slug="@Model.Name" class="btn btn-success specialButn">Show Employees</a>
    <a asp-controller="Companies" asp-action="CompanyInterns" asp-route-id="@Model.Id" asp-route-slug="@Model.Name" class="btn btn-info specialButn">Show Interns</a>
    <a asp-controller="Companies" asp-action="Edit" asp-route-id="@Model.Id" asp-route-slug="@Model.Name" class="btn btn-primary specialButn">Edit Company</a>
    <a asp-controller="Companies" asp-action="Delete" asp-route-id="@Model.Id" asp-route-slug="@Model.Name" class="btn btn-danger specialButn">Delete Company</a>
</div>

CompanyRegister.Web/Views/Companies/Edit.cshtml
@model Company
@{
    ViewData["Title"] = $"Edit {Model.Name}";
}

<div class="signup-form" style="margin-top: 55px;">
    <form asp-controller="Companies" asp-route-id="@Model.Id" asp-action="Edit" method="post" style="border-top: 1px #EEEEEE solid">
        <h2>Edit @Model.Name</h2>
        <p>Please fill in this form to edit @Model.Name!</p>
        <hr>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"></span>
                <input type="text" class="form-control" placeholder="@Model.Name" disabled="disabled">
                <input type="text" class="form-control" name="Name" placeholder="Name">
            </div>
            <span class="text-danger">@Html.ValidationMessage("Name")</span>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"></span>
                <input type="text" class="form-control" placeholder="@Model.FoundationDate.ToShortDateString()" disabled="disabled">
                <input type="date" class="form-control" name="FoundationDate" placeholder="Foundation Date">
            </div>
            <span class="text-danger">@Html.ValidationMessage("FoundationDate")</span>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"></span>
                <input type="text" class="form-control" placeholder="@Model.PictureUrl" disabled="disabled">
                <input type="text" class="form-control" name="PictureUrl" placeholder="Picture Url">
            </div>
            <span class="text-danger">@Html.ValidationMessage("PictureUrl")</span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg" style="padding: 15px;">Save Changes</button>
        </div>
    </form>
</div>
@if (ViewData.ContainsKey("edit"))
{
    <div class="alert alert-success text-center" style="width: 50%;margin: auto">
        <strong>Success!</strong> @ViewData["edit"]
    </div>
}

CompanyRegister.Web/Views/Companies/FinalDelete.cshtml
@model FinalDeleteNameDTO
@{
    ViewData["Title"] = "Final Delete";
}
<h2 class="text-center" style="margin-top: 55px;">Company removal page</h2>
<div class="alert alert-success text-center" style="width: 50%; margin: auto; margin-top: 25px; font-size: 20px;">
    <strong>Success!</strong> Company @Model.Name deleted successfully!
</div>

CompanyRegister.Web/Views/Companies/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model List<Company>

<h2 id="compH">Welcome to the companies managing page!</h2>

<div class="text-center">
    <a id="registerButton" asp-controller="Companies" asp-action="Register" class="btn btn-success">Register Company</a>
    <a id="listAllButton" asp-controller="Companies" asp-action="All" class="btn btn-info">All companies</a>
</div>
<h3 style="margin-top: 25px;">Last few registered companies:</h3>

@if (Model.Any())
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Empoyees Count</th>
                <th>Interns Count</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var company in Model)
            {
                <tr>
                    <td>
                        @company.Name
                    </td>
                    <td>
                        @company.Employees.Count()
                    </td>
                    <td>
                        @company.Interns.Count()
                    </td>
                    <td>
                        <a class="btn btn-primary" asp-controller="Companies" asp-action="Details" asp-route-id="@company.Id" asp-route-slug="@company.Name">Info</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h4 style="margin-top: 25px;font-weight: bolder">There are no companies registered! Be the first one to register one?</h4>
}

CompanyRegister.Web/Views/Companies/Register.cshtml
@{
    ViewData["Title"] = "Register";
}

<div class="signup-form" style="margin-top: 55px;">
    <form asp-controller="Companies" asp-action="Register" method="post" style="border-top: 1px #EEEEEE solid">
        <h2>Register company</h2>
        <p>Please fill in this form to register a company!</p>
        <hr>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"></span>
                <input type="text" class="form-control" name="Name" placeholder="Name" required="required">
            </div>
            <span class="text-danger">@Html.ValidationMessage("Name")</span>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"></span>
                <input type="date" class="form-control" name="FoundationDate" placeholder="Foundation Date" required="required">
            </div>
            <span class="text-danger">@Html.ValidationMessage("FoundationDate")</span>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"></span>
                <input type="text" class="form-control" name="PictureUrl" placeholder="Picture Url" required="required">
            </div>
            <span class="text-danger">@Html.ValidationMessage("PictureUrl")</span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-lg" style="padding: 15px;">Register</button>
        </div>
    </form>
</div>